apiVersion: apps/v1
kind: Deployment
metadata:
  name:  practica-optativa
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  practica-optativa
  template:
    metadata:
      labels:
        app:  practica-optativa
    spec:
      containers:
      - name: practica-optativa
        image:  practica-optativa:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80